{{- with .Values.compliance }}
{{- if .enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Release.Name }}-compliance
  labels:
    app: {{ $.Release.Name }}-compliance
spec:
  replicas: {{ default "1" .replicas | int }}
  selector:
    matchLabels:
      name: {{ $.Release.Name }}-compliance
  template:
    metadata:
      labels:
        name: {{ $.Release.Name }}-compliance
        app: {{ $.Release.Name }}-compliance
        {{- with ($.Values.podOptions).labels }}
        {{- toYaml . | indent 8 }}
        {{- end }}
      {{- with ($.Values.podOptions).annotations }}
      annotations:
        {{- toYaml . | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ $.Release.Name }}-sa
      {{- with ($.Values.podOptions).nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ($.Values.podOptions).tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: compliance
          {{- $imageTagDelimiter := ":" }}
          {{- if (hasPrefix "sha256:" .tag) }}
            {{- $imageTagDelimiter = "@" }}
          {{- end }}
          {{-
            $imageString := (
              printf "%s%s%s%s"
                (default "ghcr.io/vso-inc/" .Values.registry)
                (.repository)
                ($imageTagDelimiter)
                (default "latest" .tag)
            )
          }}
          image: {{ $imageString }}
          imagePullPolicy: {{ default "Always" $.Values.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-cm
            {{- if (.secret).create }}
            - secretRef:
                name: {{ $.Release.Name }}-compliance-secret
            {{- else if (.secret).name }}
            - secretRef:
                name: {{ .secret.name }}
            {{- else }}
            {{- fail "compliance.api.secret.name must be set if compliance.api.secret.create is false" }}
            {{- end }}
          {{- $port := .port | int }}
          env:
            - name: PORT
              value: {{ $port | quote }}
            {{- if .env }}
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- with .secretRef }}
            {{- range $key, $val := . }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.name }}
                  key: {{ $val.key }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ $port }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- include "foglifter.probe" (dict "probe" . "port" $port) | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- include "foglifter.probe" (dict "probe" . "port" $port) | nindent 12 }}
          {{- end }}
          {{- with .startupProbe }}
          startupProbe:
            {{- include "foglifter.probe" (dict "probe" . "port" $port) | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- default dict . | toYaml | nindent 12 }}
          {{- end }}
      {{- if (ne ($.Values.priorityClass).create false) }}
      priorityClassName: {{ $.Release.Name }}
      {{- end }}
{{- end }}
{{- end }}
