apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-routing-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ include "traefik.hosts" .Values }}{{ include "traefik.path" .Values.routing }}
      kind: Rule
      services:
        - name: {{ default "foglifter-routing-svc" (.Values.routing).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.routing).port | int }}
  {{- if (eq (.Values.certificate).useExisting true ) }}
  tls:
    secretName: {{ default "foglifter-traefik-cert" (.Values.certificate).name }}
  {{- end }}
