kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-routing-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ default "ClusterIP" (.Values.service).type }}
  {{- $port := default "8080" (.Values.routing).port | int }}
  ports:
  - port: {{ $port }}
    targetPort: {{ $port }}
  selector:
    name: {{ .Release.Name }}-routing
