{{- if .Values.createMongoSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: foglifter-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
