apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-routing-http
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "traefik.hosts" .Values }}{{ include "traefik.path" .Values.routing }}
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ default "foglifter-routing-svc" (.Values.routing).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.routing).port | int }}
    {{- if .Values.traefikService }}
    - match: {{ printf "Host(`%s`) && " .Values.traefikService }}{{ include "traefik.path" .Values.routing }}
      kind: Rule
      services:
        - name: {{ default "foglifter-routing-svc" (.Values.routing).name }}
          namespace: {{ default "foglifter" .Values.foglifterNamespace }}
          port: {{ default "8080" (.Values.routing).port | int }}
    {{- end }}
